-- 1. Tabla de Perfiles para guardar las variables financieras globales
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  annual_budget numeric default 31200,
  monthly_income numeric default 4500,
  current_cash numeric default 18500,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Tabla de Transacciones mapeada a tu interfaz de TypeScript
create table transactions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  date date not null,
  description text not null,
  category text not null,
  type text check (type in ('income', 'expense')) not null,
  original_amount numeric not null,
  original_currency text not null,
  exchange_rate numeric not null,
  amount_usd numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Tabla para el Action Center (Ruta Crítica)
create table tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text not null,
  completed boolean default false,
  blocked boolean default false,
  blocker_description text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ACTIVAR ROW LEVEL SECURITY (RLS)
alter table profiles enable row level security;
alter table transactions enable row level security;
alter table tasks enable row level security;

-- POLÍTICAS DE SEGURIDAD
create policy "Usuarios ven su propio perfil" on profiles for select using (auth.uid() = id);
create policy "Usuarios actualizan su propio perfil" on profiles for update using (auth.uid() = id);

create policy "Usuarios ven sus transacciones" on transactions for select using (auth.uid() = user_id);
create policy "Usuarios insertan sus transacciones" on transactions for insert with check (auth.uid() = user_id);
create policy "Usuarios borran sus transacciones" on transactions for delete using (auth.uid() = user_id);

create policy "Usuarios gestionan sus tareas" on tasks for all using (auth.uid() = user_id);
alter table tasks 
add column if not exists impact text default 'medium',
add column if not exists due_date date;

-- 1. Activar la extensión de vectores
create extension if not exists vector;

-- 2. Crear tabla de documentos/conocimiento (para notas, transacciones enriquecidas, etc.)
create table if not exists financial_memory (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  content text not null, -- El texto legible (ej: "Gasto de $50 en Cena con clientes")
  metadata jsonb, -- Datos extra (fecha, categoria, id_transaccion)
  embedding vector(1536) -- El "cerebro" numérico (OpenAI usa 1536 dimensiones)
);

-- 3. Función para buscar por similitud (La magia del RAG)
create or replace function match_financial_memory (
  query_embedding vector(1536),
  match_threshold float,
  match_count int,
  p_user_id uuid
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    financial_memory.id,
    financial_memory.content,
    financial_memory.metadata,
    1 - (financial_memory.embedding <=> query_embedding) as similarity
  from financial_memory
  where 1 - (financial_memory.embedding <=> query_embedding) > match_threshold
  and financial_memory.user_id = p_user_id
  order by financial_memory.embedding <=> query_embedding
  limit match_count;
end;
$$;
-- Habilitar RLS en la tabla
alter table financial_memory enable row level security;

-- Política para INSERTAR (El usuario puede guardar sus recuerdos)
create policy "Users can insert their own memories" 
on financial_memory for insert 
with check (auth.uid() = user_id);

-- Política para LEER (El usuario solo ve sus propios recuerdos)
create policy "Users can read their own memories" 
on financial_memory for select 
using (auth.uid() = user_id);

-- Política para BORRAR (Opcional, por si necesitas limpiar)
create policy "Users can delete their own memories" 
on financial_memory for delete 
using (auth.uid() = user_id);

-- Crear índice único compuesto
-- Si intentas insertar una fila con la misma combinación de estos 5 campos, la DB lo rechazará.
ALTER TABLE transactions
ADD CONSTRAINT unique_transaction_entry 
UNIQUE (user_id, date, description, original_amount, type);